# Grafana Datasources Provisioning
# Automatically configure data sources on startup

apiVersion: 1

datasources:
  # Prometheus - Primary metrics store
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: "2.45.0"
    version: 1

  # PostgreSQL - Direct database access for custom queries
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: festival
    user: festival_readonly
    secureJsonData:
      password: ${POSTGRES_READONLY_PASSWORD}
    jsonData:
      sslmode: require
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    editable: false
    version: 1

  # Redis - For real-time data
  - name: Redis
    type: redis-datasource
    url: redis:6379
    jsonData:
      client: standalone
      poolSize: 5
    secureJsonData:
      password: ${REDIS_PASSWORD}
    editable: false
    version: 1

  # Loki - Log aggregation (if deployed)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    editable: false
    version: 1

  # Alertmanager - Alert management
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    jsonData:
      implementation: prometheus
    editable: false
    version: 1
